// <auto-generated />
namespace OgameBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlanetCoords_Computed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlanetCoords_Computed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704012025426_PlanetCoords_Computed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
